version: '3'
services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: backend-movies-reviews
    volumes:
      - ./mongo:/data/db